# api-webpay-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-webpay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-webpay
  template:
    metadata:
      labels:
        app: api-webpay
    spec:
      containers:
      - name: api-webpay
        image: gcr.io/annular-form-401215/api-webpay:v1
        ports:
        - containerPort: 8080